### ISSUE TITLE
does not convert philips DTI dcm files

### ISSUE THREAD

**Issue by mrjeffs** [moloney/dcmstack#48]
pointed dcmstack to directory of 1 DTI scan and got confused on 4th dimention. cmd:
dcmstack -v DTI_2p5DB_SOME_NOISE
Processing source directory DTI_2p5DB_SOME_NOISE
Found 1088 source files in the directory
Found 1 groups of DICOM images
Writing out stack to path DTI_2p5DB_SOME_NOISE/301-DTI_2.5DB_SOME_NOISE_SENSE.nii.gz
Traceback (most recent call last):
  File "/home/toddr/Software/anaconda2/bin/dcmstack", line 9, in <module>
    load_entry_point('dcmstack', 'console_scripts', 'dcmstack')()
  File "/home/toddr/Software/dcmstack/src/dcmstack/dcmstack_cli.py", line 324, in main
    nii = stack.to_nifti(args.voxel_order, gen_meta)
  File "/home/toddr/Software/dcmstack/src/dcmstack/dcmstack.py", line 857, in to_nifti
    data = self.get_data()
  File "/home/toddr/Software/dcmstack/src/dcmstack/dcmstack.py", line 763, in get_data
    stack_shape = self.get_shape()
  File "/home/toddr/Software/dcmstack/src/dcmstack/dcmstack.py", line 726, in get_shape
    raise InvalidStackError("Unable to guess key for sorting the "
dcmstack.dcmstack.InvalidStackError: The DICOM stack is not valid: Unable to guess key for sorting the fourth dimension

**Comment by anbai106** [comment]
I have the same erreur when converting DTI dcm of philips, dcmstack works well for Siemens and GE(all for DTI, phase and magnitude images)

Do you have any solution???

Thanks in advance

**Comment by moloney** [comment]
Since I already replied to #51 I am going to close this one. Lets continue the conversation over there.
